# Generated by Django 5.1.6 on 2025-02-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriýa ady')),
                ('img', models.ImageField(upload_to='category_images/')),
            ],
            options={
                'verbose_name': 'kategoriýa',
                'verbose_name_plural': 'kategoriýalar',
                'db_table': 'category',
            },
        ),
    ]
