# Generated by Django 5.1.6 on 2025-02-17 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(upload_to='category_images/', verbose_name='surat saýla'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='slug (boş durubersin)'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Element ady')),
                ('img', models.ImageField(upload_to='items/', verbose_name='surat saýla')),
                ('description', models.TextField(verbose_name='Element barada düşündiriş')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.category', verbose_name='Kategoriýa saýla')),
            ],
            options={
                'verbose_name': 'Element',
                'verbose_name_plural': 'Elementler',
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='ItemFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='item_files', verbose_name='Element faýllaryny ýükle')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.item', verbose_name='Faýl elementini saýla')),
            ],
            options={
                'verbose_name': 'Faýl',
                'verbose_name_plural': 'Faýllar',
                'db_table': 'files',
            },
        ),
    ]
