# Generated by Django 5.1.6 on 2025-02-17 09:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_category_img_alter_category_slug_item_itemfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Element barada düşündiriş'),
        ),
    ]
