# Generated by Django 5.1.6 on 2025-02-17 09:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=ckeditor.fields.RichTextField(default='10', verbose_name='Element barada düşündiriş'),
        ),
    ]
