# Generated by Django 5.1.6 on 2025-02-18 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sargyt ediji')),
                ('phone', models.CharField(max_length=25, verbose_name='telefon belgisi')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='senesi')),
            ],
            options={
                'verbose_name': 'sargyt',
                'verbose_name_plural': 'sargytlar',
                'db_table': 'order',
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default=10, max_length=15, verbose_name='Bahasyny giriz.(dine san giriz)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='slug (boş durubersin)'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
            options={
                'verbose_name': 'sargyt',
                'verbose_name_plural': 'sargyt',
                'db_table': 'orderitem',
            },
        ),
    ]
