# Generated by Django 5.1.6 on 2025-02-25 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_orderitem_options_alter_orderitem_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfile',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='api.item', verbose_name='Faýl elementini saýla'),
        ),
    ]
